### ISSUE TITLE
Images used for training the provided models ?

### ISSUE THREAD

**Issue by bgalerne** [JWSoh/NatSR#4]
Hi,

I found your paper really interesting. Could you please provide information regarding the datasets used to train the provided model, especially NatSR ?
Is it DIV2K_train_HR / DIV2K_train_LR_bicubic_X4 ?

Best regards,

Bruno

**Comment by JWSoh** [comment]
Yes, we just have used DIV2K_train_HR / DIV2K_train_LR_bicubic_X4 for training NatSR.

**Comment by bgalerne** [comment]
Thank you for the information.
