### ISSUE TITLE
Error on using 2x and 3x models for inference

### ISSUE THREAD

**Issue by nelaturuharsha** [JWSoh/NatSR#9]
Hello,
Thank you so much for the excellent algorithm and open sourcing the code. I was attempting to run inference using the parameters specified, just wanted to note a few issues and queries
1. I needed to set save to "True" explicitly to save the images.
2. On attempting to use the 2x and 3x problems, I had problems w.r.t to the graph, is there anything else that needs to be edited in the test script to run inference with those models?

Output for NatSR and FRSR always turns out to be a white image with some edges, any fix for the same?

**Comment by JWSoh** [comment]
We have fixed the code, please try again

**Comment by nelaturuharsha** [comment]
Thank you so much for the response, will try again.
